version: "3.9"

services:
  app:
    container_name: gpt-works-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/gpt-works

  web:
    container_name: gpt-works-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./:/var/www/gpt-works

  db:
    container_name: gpt-works-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 13361:3306
    environment:
      MYSQL_DATABASE: gpt-works_db
      MYSQL_USER: baritech
      MYSQL_PASSWORD: baritech
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
      
volumes:
  mysql-volume:
    external:
      name: gpt-works-db_volume